name: CI

on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - uses: actions/cache@v1.1.0
      with:
        path: ./Library
        key: Library
        restore-keys: |
          Library-
    - uses: chankiyu22/unity-test-runner@v1.6-chankiyu22-dev
      id: tests
      with:
        unityVersion: 2018.3.0f2
        testMode: editmode
    - uses: actions/upload-artifact@v1
      if: ${{ success() || failure() }}
      with:
        name: Test results
        path: ${{ steps.tests.outputs.artifactsPath }}
    - uses: chankiyu22/unity-test-result-pretty-print@v0.0.1
      if: ${{ success() || failure() }}
      with:
        path: ${{ steps.tests.outputs.artifactsPath }}
